name: PHP Compatibility 8.2

on:
  push:

permissions:
  contents: read

jobs:
  setup:
    name: php compatibility 8.2
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP Setup 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2-'
          coverage: none

      - name: php-compatibility run
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: '8.2-'
          paths: ${{ github.workspace }}/Plugin.php ${{ github.workspace }}/Controller/ ${{ github.workspace }}/Locale/ 
