name: PHP 7.4

on:
  push:
  pull_request:
    branches: [master, main]

permissions:
  contents: read

jobs:
  setup:
    name: Scan Code
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP Setup 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4-'
          ini-values: short_open_tag=On
          coverage: none

      - name: Run PHP Compatibility
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: '7.4-'
          paths: ${{ github.workspace }}/Plugin.php ${{ github.workspace }}/Controller/ ${{ github.workspace }}/Locale/ ${{ github.workspace }}/Helper/ ${{ github.workspace }}/Template/
